---
title: "flextest"
output: flexdashboard::flex_dashboard
date: '2022-11-03'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(plotly)
library(ggplot2)
library(htmlwidgets)
library(crosstalk)

sData <- SharedData$new(mtcars)
sNames <- SharedData$new(data.frame(names = names(mtcars)))
```

Column {dat-width=500}
--------------  

### Inputs

```{r}
filter_select("column1", "Column 1", sNames, ~names, multiple = TRUE)

```



Column {dat-width=500}
--------------

### Plot

```{r}
p <- plot_ly(data = sData$data())

nvars <- 5 #length(names(mtcars))
t_matrix <- matrix(rep(c(rep(T, times = nvars), rep(F, times = nvars)), times = nvars^2)[1:(nvars^3)] | rep(c(rep(c(T, rep(F, times = nvars-1)), times = nvars), F), times = nvars)[1:(nvars^3)], nvars, nvars*nvars, byrow = TRUE)


for (x in names(mtcars))
  for (y in names(mtcars))
           p <- add_trace(type = "scatter", x = ~!!sym(x), y = ~!!sym(y), mode = "markers", visible = F)

items <- lapply(seq_along(mtcars), function (x) list(label=mtcars[x], args=list(list(visible ))))
```

